### ISSUE TITLE
замечания 2

### ISSUE THREAD

**Issue by Frederic-Chur** [RedHeadIvan/ReleaseDocGOST#1]
Разные подходы к форматированию рефдесов в ПЭ и СБ
предлагаю убрать пробел между рефдесами в спецификации, в этом случае резко уменьшится кол-во листов

![ПЭ](https://user-images.githubusercontent.com/82882032/115394683-b15d4b80-a1eb-11eb-9b21-e2b5b6bcf554.png)
![СБ](https://user-images.githubusercontent.com/82882032/115394688-b1f5e200-a1eb-11eb-83b9-d5035a395850.png)

**Comment by RedHeadIvan** [comment]
Для единства формата будут добавлены пробелы в ПЭ3. Удаления пробелов в спецификации не имеет смысла, т.к. при 100+ компонентах все равно три позиции в строку не уместятся и экономия будет минимальной
