### ISSUE TITLE
Bug неправильный парсинг

### ISSUE THREAD

**Issue by fig-05** [RedHeadIvan/ReleaseDocGOST#11]
Если в проекте есть куча одинаковых элементов и в последствии один из них был удален, то потом список формируется не корректно. На примере/картинке отсутствует C13.

![bug](https://user-images.githubusercontent.com/86650706/123754904-0ab8b980-d8c4-11eb-91d0-9503365e300c.jpg)

**Comment by RedHeadIvan** [comment]
На сколько мне известно, и как было заложено, ЕСКД не предусматривает пропусков в нумерации. Функция исключения из списка заложена в закрытой бета-версии, но такого подхода не предполагает. Делайте ренамбер, чтобы все шло последовательно

**Comment by fig-05** [comment]
У нас иногда встречаются сложные проекты с очень большим количеством компонентов и эти проекты потом проходят сертификацию на степень безопасности SIL3. Для этого уже другие люди рассчитывают надежность по каждому элементу. Если сделать перенумерацию при небольших изменениях в схеме, то все расчеты придется корректировать, а это крайне трудоёмко. Поэтому зачастую не делаем перенумерацию.
У вас очень классная задумка, на деюсь в будущем появится может галочка учитывать пропуск компонентов или такие строки как-то выделять, чтобы потом визуально их заметить и в ручную отредактировать.
Заранее спасибо.

**Comment by Andy-Smir** [comment]
Если элемент удаляется со схемы по какой-то причине то в перечне указывается в примечании - "не ставить". На схеме при этом элемент маркируется звездочкой и в примечаниях или комментариях указывается что элемент не ставится и кратенько указывается причина, вроде "по результатам настройки -регулировки"
