### ISSUE TITLE
Некорректный парсинг проекта DxD

### ISSUE THREAD

**Issue by Frederic-Chur** [RedHeadIvan/ReleaseDocGOST#2]
При Генерация из проекта DxDesigner (Файл > Импорт данных > Проект Mentor Graphics) информация извлекается только из открытых листов

необходимо :
1.DocGOST должен открыть все листы
2.если не возможно выполнить п.1 предупредить об этом, что "все листы д.б. открыты"

**Comment by Andy-Smir** [comment]
1. Не работает "Генератор БД MG"
2. Пожелание: Добавить возможность вывода в текстовом формате. При этом необходимо иметь возможность задания разделителей строк(запятая, пробел, точка с запятой, двоеточие, пробел, табуляция и тд). При выводе необходимо соблюдать форматирование исходного документа. (перечень, ВП, спецификация)

**Comment by RedHeadIvan** [comment]
Исправлено
