### ISSUE TITLE
Выгрузка данных в табличном виде

### ISSUE THREAD

**Issue by Andy-Smir** [RedHeadIvan/ReleaseDocGOST#5]
Пожелание: Добавить возможность вывода в текстовом формате. При этом необходимо иметь возможность задания разделителей строк(запятая, пробел, точка с запятой, двоеточие, пробел, табуляция и тд). При выводе необходимо соблюдать форматирование исходного документа. (перечень, ВП, спецификация)

**Comment by RedHeadIvan** [comment]
Реализовано
