### ISSUE TITLE
Предложение по оформлению ВП

### ISSUE THREAD

**Issue by Andy-Smir** [RedHeadIvan/ReleaseDocGOST#6]
При оформлении неплохо иметь возможность указывать количество элементов на регулировку. Соответственно в графе "Всего" должна быть сумма граф "На изделие" и "На регулировку". Обычно на регулировку берут 10 процентов от количества которое идет на изделие с последующим округлением в большую сторону. Например на изделие идет 1 элемент, 10% от него будет 0.1 соответственно на регулировку получается 1 всего покупается 2.
 Можно ввести возможность ввода коэффициента количества требуемых элементов на регулировку.  Если коэффициент равен "0" то на регулировку ни чего не предусмотрено, если 100% то покупается двойное количество (при этом полученное число элементов округляется в большую сторону).

**Comment by RedHeadIvan** [comment]
Реализовано в виде базово задаваемого процента запаса, распространяется на все компоненты
