### ISSUE TITLE
Пожелание, Атрибут "Part List Exclude".

### ISSUE THREAD

**Issue by Andy-Smir** [RedHeadIvan/ReleaseDocGOST#7]
При получении данных с проекта неплохо учитывать атрибут "Part List Exclude" который позволяет определить должен элемент  входить в перечень или нет. Если значение атрибута "True" то элемент не входит в перечень элементов, если "False" то входит.

**Comment by RedHeadIvan** [comment]
Ошибку нашел, связана с Part List Exclude, добавляемыми непосредственно на схеме (не атрибут символа). Будет поправлена в следующем релизе

**Comment by RedHeadIvan** [comment]
Исправлено
