### ISSUE TITLE
Пожелание. Спецификацию можно попробовать формировать с PCB.....

### ISSUE THREAD

**Issue by Andy-Smir** [RedHeadIvan/ReleaseDocGOST#8]
Предложение связано с тем что на плате можно размещать механические компоненты, винты, гайки, радиаторы и тд.

**Comment by RedHeadIvan** [comment]
Свойств компонентов в рамках PCB может быть недостаточно для формирования КД (не все пользователи используют только Part Number), поэтому для корректной работы необходимо использовать некоторый внешний источник свойств компонентов и добавить в ДокГОСТ возможность разделять импортированные компоненты по назначению. На данный момент не совсем ясно, как это реализовать, но будет учтено в будущих релизах
